---
- name: Download for DEB
  ansible.builtin.import_tasks:
    file: repo_deb.yml
  when: ansible_os_family == "Debian"

- name: Download for RPM
  ansible.builtin.import_tasks:
    file: repo_rpm.yml
  when: ansible_os_family == "RedHat"

- name: Start and enable Docker service
  ansible.builtin.service:
    name: "{{ agent_type }}"
    state: started
    enabled: true
  when: ansible_virtualization_type != "docker"
  tags:
    - google_cloud_ops_agent
